output: "./apis"
projects:
  - name: "ucenter"
    description: "用户中心"
    services:
      - name: "auth"
        description: "权限校验服务"
        OpenAPI:
          version: "2.0"
          url: "https://accountdev.mingqi-tech.cn/api/auth-service/v2/api-docs"
      - name: "user"
        description: "用户服务"
        OpenAPI:
          version: "2.0"
          url: "https://accountdev.mingqi-tech.cn/api/user-service/v2/api-docs"
  - name: "P&L"
    description: "P&L"
    services:
      - name: "pl"
        description: "用户服务"
        OpenAPI:
          version: "3.0"
          url: "https://pl.mingqi-tech.cn/v3/api-docs"
